{% set version = "7.0.0" %}

package:
  name: dask-labextension-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_labextension/dask_labextension-{{ version }}.tar.gz
  sha256: 45a60bd0ad31c5e425986b7e40a5aa242aa582ea868025ac2b82d0aa16ffcb8a

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: dask-labextension
    build:
      noarch: python
      script:
      - {{ PYTHON }} -m pip install --no-deps -vv --no-build-isolation .
    requirements:
      host:
        - hatch-jupyter-builder >=0.5
        - hatchling
        - hatch-nodejs-version
        - jupyterlab >=4.0.0,<5
        - pip
        - python >=3.8
      run:
        - bokeh >=1.0.0,!=2.0.0
        - distributed >=1.24.1
        - jupyter-server-proxy >=1.3.2
        - jupyterlab >=4.0.0,<5
        - python >=3.8
    test:
      imports:
        - dask_labextension
      requires:
        - m2-grep  # [win]
        - pip
      commands:
        - pip check
        - jupyter labextension list
        - jupyter server extension list
        - jupyter labextension list 1>labextensions 2>&1
        - jupyter server extension list 1>server_extensions 2>&1
        - grep -iE "dask-labextension.*OK.*dask_labextension" labextensions
        - grep -iE "dask_labextension.*OK" server_extensions
        - dir %PREFIX%\share\jupyter\labextensions\dask-labextension\schemas\dask-labextension\plugin.json || exit 1  # [win]
        - ls ${PREFIX}/share/jupyter/labextensions/dask-labextension/schemas/dask-labextension/plugin.json  # [not win]

  - name: dask_labextension
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage('dask-labextension', max_pin='x.x.x') }}
    test:
      imports:
        - dask_labextension

about:
  home: https://github.com/dask/dask-labextension
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - dask_labextension/labextension/static/third-party-licenses.json
  summary: A JupyterLab extension for Dask.

extra:
  feedstock-name: dask-labextension
  recipe-maintainers:
    - xhochy
    - ocefpaf
    - jsignell
    - bollwyvl
