{% set version = "2.0.1" %}

package:
  name: dask-labextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_labextension/dask_labextension-{{ version }}.tar.gz
  sha256: 50f232b1030a32b0e1c63f48f5d74e2fc1feca1a951b81de77b7d02dc84bfda7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    # distributed and notebook are directly imported by setup.py
    - distributed >=1.24.1
    - notebook >=4.3.1
  run:
    - python >=3.6
    - bokeh
    - distributed >=1.24.1
    - notebook >=4.3.1
    - jupyter-server-proxy >=1.1.0

test:
  imports:
    - dask_labextension
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/dask-labextension
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter Notebook server extension manages Dask clusters

extra:
  recipe-maintainers:
    - xhochy
    - ocefpaf
