travis:
  secure:
    BINSTAR_TOKEN: AxZNX7GeaZqq+Bt8o+OFKkRkielraGfjdF58wxvAmuGErASvRPRwTdJoyNA3m/p3cMLs+fUQVmJwjDrXsDCdfKvdL2NUP9ccoG4YV+mRFYI1ixGSnjGgjo7R9eqI6b/CmDu0NRLziRPrrPnaKaStwgQmyL7VNzVErfxESrEvsn5gTpwbf0OvOs7XUgWaA/u/zdsHYBDGQJSQgP33oAYyRdy596Hb/bbYKLlE2qlZEwP5uM1s+Gz+wn24IS6gqzXm77W/omZqIl6mxJKyIlpZ6OP57xPJWBWKq1d+KYRSMXlzl7Y8EOuPe6pBOCtzUGjBQegRu0lwr8LjWW2OdQS6OUr2SBZcrLR9oFXSvJy60ofr+5rAdQbuRCQ4jqgxZ/tfcMQEG2VAfZhsJbvd5Z5pqlL2uBjfS2umPnek1/CRb2RnNh1gT5WK+SoEIpsTDzT/xP23BRoTUr54MvE6D277D4O22AHtrUpC5N/BLM4Tnx/ZxleCvw4cfvaAndEd+CMRJDpI7iCFZ1ez+deYNqIsl8HdXoezKlvcWpr6Dtgx1vdCiESqGAWlKzvfwtZ7Gnw385YyHL7ddbc4solDNhc1OFs9225oXaAMbBrLXnADq+ibGDWki1dWCoey5zxNsFslmF1FFrFK8xH4Ij2C6AsJbw7YpFSUyZhcsnHT7K8edMg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
